image: node:10.12.0

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - setup
  - build
  - test
  - deploy

setup:
  stage: setup
  script:
    - npm install
  cache:
    paths:
    - node_modules/

eslint:
  stage: build
  script:
    - npm install -g eslint
    - npm run lint
