image: node:10.12.0

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

setup:
  stage: build
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - npm install

eslint:
  stage: test
  script:
    - npm install -g eslint
    - npm run lint

deploy:
  only:
    - master
  stage: deploy
  script:
    - bash deploy/deploy.sh